version: '3.7'
services:
  paperboy:
    environment:
      PORT: 8787
      DEBUG: "true"
      GOOGLE_GEOCODING_APIKEY: "AIzaS...api_key"
    build:
      context: .
      dockerfile: Dockerfile
    restart: always
    ports:
      - "8787:8787"
